language: python
python:
 - "3.5"
 - "3.7"

services:
 - docker

before_script: pip install docker-compose

script: 
 - docker-compose -f docker-compose.yml run -e COVERALLS_REPO_TOKEN web sh -c "coverage run ./src/manage.py test src && flake8 src && coveralls"