version: '2.2'

###############################################################################
#
# FOR DOCKER-COMPOSE SETTINGS SPECIFIC TO PRODUCTION
#
# Run with:
# `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d`
#
# https://docs.docker.com/compose/extends/
################################################################################

services:
  web:
    command: bash -c "cd /app/src/ &&
                      python manage.py migrate_schemas --shared &&
                      python manage.py migrate_schemas --executor=parallel && 
                      python manage.py collectstatic --noinput &&
                      uwsgi --ini uwsgi.ini"
    volumes: 
      - .:/app
      - /var/www/bytedeck/media/:/app/media
      - /var/www/bytedeck/static/:/app/static
    user: $WUID:$WGID
  celery:
    user: $WUID:$WGID