version: '2.2'

###############################################################################
#
# FOR DOCKER_COMPOSE SETTINGS SPECIFIC TO DEVELOPMENT
# 
# It is run automatically with `docker-compose up` on top of the the settings in docker-compose.yml
#
# docker-compose.overide.yml
# https://docs.docker.com/compose/extends/
################################################################################

services:
  db:
    ports:
    - 5432:5432  # Expose port so app can connect to db when developing locally with `./src/manage.py [runserver|test src]
  redis:
    ports:
    - 6379:6379  # Expose port so app can connect to redis when developing locally with `./src/manage.py [runserver|test src]
  web:
    command: bash -c "cd /app/src/ &&
                      python manage.py migrate_schemas --shared &&  
                      python manage.py migrate_schemas --executor=parallel && 
                      python manage.py runserver 0.0.0.0:8000"   # no need for uwsgi in development, this is easier

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
