version: '2' # supported by default isntall on Ubuntu 18.04

services:
  db:
    image: postgres:9.5-alpine # Production server is using 9.5.17
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:5.0-alpine" # Production server is using 3.0.6
    ports:
    - 6379:6379
  web:
    #restart: unless-stopped
    build: . # current directory
    env_file: 
      .env
    command: bash -c "python /app/src/manage.py migrate && 
                      python /app/src/manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file: .env
    # run both workers and beat (with "-B" development environment only per celery docs)
    # https://django-celery-beat.readthedocs.io/en/latest/
    command: bash -c "cd src &&
                      celery -A hackerspace_online worker -l info -c 3 -Q default --beat --scheduler django --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  
# Does this transfer to the non-containered code?
