version: '3.7'

services:
  web:
    build: . # current directory
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
#     depends_on:
#       - db    
  
#   db:
#     image: postgres:11-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:
  
